apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kzowy9kg0-python
  janus-idp.io/tekton: kzowy9kg0-python
  backstage.io/kubernetes-id: kzowy9kg0-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kzowy9kg0-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
